# Generated by Django 3.0.8 on 2020-08-10 01:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Proyecto_ORM', '0002_auto_20200808_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateField(default=datetime.date(2020, 8, 9), verbose_name='Fecha'),
        ),
    ]
